### ISSUE TITLE
请问如何能把Excel文件统一放进一个文件夹？

### ISSUE THREAD

**Issue by Wecica** [yanghuan/proton#8]
python小白，试着把EXPORT_FILES里面的文件名加改成了
EXPORT_FILES = [
"excels/hero.xlsx",
"excels/mount.xlsx"
]
结果报错说Permission denied: 'excels'.
请大佬指教。

**Comment by yanghuan** [comment]
试试 "excels\\hero.xlsx"

**Comment by Wecica** [comment]
还是不行，不管是正斜，反斜，反斜加反斜，反斜加正斜，都不行。。。

**Comment by Wecica** [comment]
发现是proton.py第300行paths在分割文件的时候里面包含了‘/’，我把这里的‘/’去掉了，目前是没问题了，但不知道有没有什么影响，望指教。

**Comment by yanghuan** [comment]
对的，这里分隔符不应该考虑路径分隔符，多谢反馈，我也修改下------------------ 原始邮件 ------------------发件人: Wecica  <notifications@github.com>发送时间: 2020年4月28日 10:51收件人: yanghuan/proton <proton@noreply.github.com>抄送: YANG Huan <sy.yanghuan@gmail.com>, Comment <comment@noreply.github.com>主题: 回复：[yanghuan/proton] 请问如何能把Excel文件统一放进一个文件夹？ (#8)
发现是proton.py第300行paths在分割文件的时候里面包含了‘/’，我把这里的‘/’去掉了，目前是没问题了，但不知道有没有什么影响，望指教。

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/yanghuan/proton/issues/8#issuecomment-620346212",
"url": "https://github.com/yanghuan/proton/issues/8#issuecomment-620346212",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yanghuan** [comment]
fix by c28c53946ad56e67fa1f5e44f53988fbb4fe50a1
